Public Class Study

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Me.Controls.Remove(Button1)
        Me.Controls.Remove(Button2)
        Me.Controls.Remove(Button3)
        Me.Controls.Remove(Button4)
        Me.Controls.Remove(Button5)
        Me.Controls.Remove(Button6)
        Me.Controls.Remove(Button7)
        Me.Controls.Remove(Button8)
        Me.Controls.Remove(Button9)
        Me.Controls.Remove(Button10)
        Me.Controls.Remove(Button11)
        Me.Controls.Remove(Button12)
        Me.Controls.Remove(Button13)
        Me.Controls.Remove(Button14)
    End Sub

    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        Me.Controls.Remove(Button1)
        Me.Controls.Remove(Button2)
        Me.Controls.Remove(Button3)
        Me.Controls.Remove(Button4)
        Me.Controls.Remove(Button5)
        Me.Controls.Remove(Button6)
        Me.Controls.Remove(Button7)
        Me.Controls.Remove(Button8)
        Me.Controls.Remove(Button9)
        Me.Controls.Remove(Button10)
        Me.Controls.Remove(Button11)
        Me.Controls.Remove(Button12)
        Me.Controls.Remove(Button13)
        Me.Controls.Remove(Button14)
    End Sub

    Private Sub Button3_Click(sender As Object, e As EventArgs) Handles Button3.Click
        Me.Controls.Remove(Button1)
        Me.Controls.Remove(Button2)
        Me.Controls.Remove(Button3)
        Me.Controls.Remove(Button4)
        Me.Controls.Remove(Button5)
        Me.Controls.Remove(Button6)
        Me.Controls.Remove(Button7)
        Me.Controls.Remove(Button8)
        Me.Controls.Remove(Button9)
        Me.Controls.Remove(Button10)
        Me.Controls.Remove(Button11)
        Me.Controls.Remove(Button12)
        Me.Controls.Remove(Button13)
        Me.Controls.Remove(Button14)
    End Sub

    Private Sub Button4_Click(sender As Object, e As EventArgs) Handles Button4.Click
        Me.Controls.Remove(Button1)
        Me.Controls.Remove(Button2)
        Me.Controls.Remove(Button3)
        Me.Controls.Remove(Button4)
        Me.Controls.Remove(Button5)
        Me.Controls.Remove(Button6)
        Me.Controls.Remove(Button7)
        Me.Controls.Remove(Button8)
        Me.Controls.Remove(Button9)
        Me.Controls.Remove(Button10)
        Me.Controls.Remove(Button11)
        Me.Controls.Remove(Button12)
        Me.Controls.Remove(Button13)
        Me.Controls.Remove(Button14)
    End Sub

    Private Sub Button5_Click(sender As Object, e As EventArgs) Handles Button5.Click
        Me.Controls.Remove(Button1)
        Me.Controls.Remove(Button2)
        Me.Controls.Remove(Button3)
        Me.Controls.Remove(Button4)
        Me.Controls.Remove(Button5)
        Me.Controls.Remove(Button6)
        Me.Controls.Remove(Button7)
        Me.Controls.Remove(Button8)
        Me.Controls.Remove(Button9)
        Me.Controls.Remove(Button10)
        Me.Controls.Remove(Button11)
        Me.Controls.Remove(Button12)
        Me.Controls.Remove(Button13)
        Me.Controls.Remove(Button14)
    End Sub

    Private Sub Button6_Click(sender As Object, e As EventArgs) Handles Button6.Click
        Me.Controls.Remove(Button1)
        Me.Controls.Remove(Button2)
        Me.Controls.Remove(Button3)
        Me.Controls.Remove(Button4)
        Me.Controls.Remove(Button5)
        Me.Controls.Remove(Button6)
        Me.Controls.Remove(Button7)
        Me.Controls.Remove(Button8)
        Me.Controls.Remove(Button9)
        Me.Controls.Remove(Button10)
        Me.Controls.Remove(Button11)
        Me.Controls.Remove(Button12)
        Me.Controls.Remove(Button13)
        Me.Controls.Remove(Button14)
    End Sub

    Private Sub Button7_Click(sender As Object, e As EventArgs) Handles Button7.Click
        Me.Controls.Remove(Button1)
        Me.Controls.Remove(Button2)
        Me.Controls.Remove(Button3)
        Me.Controls.Remove(Button4)
        Me.Controls.Remove(Button5)
        Me.Controls.Remove(Button6)
        Me.Controls.Remove(Button7)
        Me.Controls.Remove(Button8)
        Me.Controls.Remove(Button9)
        Me.Controls.Remove(Button10)
        Me.Controls.Remove(Button11)
        Me.Controls.Remove(Button12)
        Me.Controls.Remove(Button13)
        Me.Controls.Remove(Button14)
    End Sub

    Private Sub Button8_Click(sender As Object, e As EventArgs) Handles Button8.Click
        Me.Controls.Remove(Button1)
        Me.Controls.Remove(Button2)
        Me.Controls.Remove(Button3)
        Me.Controls.Remove(Button4)
        Me.Controls.Remove(Button5)
        Me.Controls.Remove(Button6)
        Me.Controls.Remove(Button7)
        Me.Controls.Remove(Button8)
        Me.Controls.Remove(Button9)
        Me.Controls.Remove(Button10)
        Me.Controls.Remove(Button11)
        Me.Controls.Remove(Button12)
        Me.Controls.Remove(Button13)
        Me.Controls.Remove(Button14)
    End Sub

    Private Sub Button9_Click(sender As Object, e As EventArgs) Handles Button9.Click
        Me.Controls.Remove(Button1)
        Me.Controls.Remove(Button2)
        Me.Controls.Remove(Button3)
        Me.Controls.Remove(Button4)
        Me.Controls.Remove(Button5)
        Me.Controls.Remove(Button6)
        Me.Controls.Remove(Button7)
        Me.Controls.Remove(Button8)
        Me.Controls.Remove(Button9)
        Me.Controls.Remove(Button10)
        Me.Controls.Remove(Button11)
        Me.Controls.Remove(Button12)
        Me.Controls.Remove(Button13)
        Me.Controls.Remove(Button14)
    End Sub

    Private Sub Button10_Click(sender As Object, e As EventArgs) Handles Button10.Click
        Me.Controls.Remove(Button1)
        Me.Controls.Remove(Button2)
        Me.Controls.Remove(Button3)
        Me.Controls.Remove(Button4)
        Me.Controls.Remove(Button5)
        Me.Controls.Remove(Button6)
        Me.Controls.Remove(Button7)
        Me.Controls.Remove(Button8)
        Me.Controls.Remove(Button9)
        Me.Controls.Remove(Button10)
        Me.Controls.Remove(Button11)
        Me.Controls.Remove(Button12)
        Me.Controls.Remove(Button13)
        Me.Controls.Remove(Button14)
    End Sub

    Private Sub Button11_Click(sender As Object, e As EventArgs) Handles Button11.Click
        Me.Controls.Remove(Button1)
        Me.Controls.Remove(Button2)
        Me.Controls.Remove(Button3)
        Me.Controls.Remove(Button4)
        Me.Controls.Remove(Button5)
        Me.Controls.Remove(Button6)
        Me.Controls.Remove(Button7)
        Me.Controls.Remove(Button8)
        Me.Controls.Remove(Button9)
        Me.Controls.Remove(Button10)
        Me.Controls.Remove(Button11)
        Me.Controls.Remove(Button12)
        Me.Controls.Remove(Button13)
        Me.Controls.Remove(Button14)
    End Sub

    Private Sub Button12_Click(sender As Object, e As EventArgs) Handles Button12.Click
        Me.Controls.Remove(Button1)
        Me.Controls.Remove(Button2)
        Me.Controls.Remove(Button3)
        Me.Controls.Remove(Button4)
        Me.Controls.Remove(Button5)
        Me.Controls.Remove(Button6)
        Me.Controls.Remove(Button7)
        Me.Controls.Remove(Button8)
        Me.Controls.Remove(Button9)
        Me.Controls.Remove(Button10)
        Me.Controls.Remove(Button11)
        Me.Controls.Remove(Button12)
        Me.Controls.Remove(Button13)
        Me.Controls.Remove(Button14)
    End Sub

    Private Sub Button13_Click(sender As Object, e As EventArgs) Handles Button13.Click
        Me.Controls.Remove(Button1)
        Me.Controls.Remove(Button2)
        Me.Controls.Remove(Button3)
        Me.Controls.Remove(Button4)
        Me.Controls.Remove(Button5)
        Me.Controls.Remove(Button6)
        Me.Controls.Remove(Button7)
        Me.Controls.Remove(Button8)
        Me.Controls.Remove(Button9)
        Me.Controls.Remove(Button10)
        Me.Controls.Remove(Button11)
        Me.Controls.Remove(Button12)
        Me.Controls.Remove(Button13)
        Me.Controls.Remove(Button14)
    End Sub

    Private Sub Button14_Click(sender As Object, e As EventArgs) Handles Button14.Click
        Me.Controls.Remove(Button1)
        Me.Controls.Remove(Button2)
        Me.Controls.Remove(Button3)
        Me.Controls.Remove(Button4)
        Me.Controls.Remove(Button5)
        Me.Controls.Remove(Button6)
        Me.Controls.Remove(Button7)
        Me.Controls.Remove(Button8)
        Me.Controls.Remove(Button9)
        Me.Controls.Remove(Button10)
        Me.Controls.Remove(Button11)
        Me.Controls.Remove(Button12)
        Me.Controls.Remove(Button13)
        Me.Controls.Remove(Button14)
    End Sub

    Private Sub Label1_Click(sender As Object, e As EventArgs)

    End Sub
End Class